name: rag-finanzas
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - nb_conda_kernels

  - pip:
      - pandas
      - datasets
      - scikit-learn

      - langchain
      - langchain-community
      - langchain-huggingface
      - chromadb
      - sentence-transformers

      - python-dotenv
      - ipykernel
      - tqdm
      - pypdf
      - pymupdf

      - rank-bm25
